[2017-09-06 11:25:57] [INFO] test start
[2017-09-06 11:26:03] [INFO] test_changeip:修改局域网ip 地址，并等待修改完重启后，新地址可以登录
[2017-09-06 11:26:03] [INFO] 准备将登录修改为：192.168.0.2
[2017-09-06 11:26:03] [INFO] 原来的登录地址为 192.168.0.1
[2017-09-06 11:27:41] [INFO] 修改成功，二次登录
[2017-09-06 11:27:50] [INFO] 登录后，进入新的配置系统，二次修改局域网ip 地址为原来的地址，
[2017-09-06 11:29:06] [INFO] test_changeip STOP
[2017-09-06 11:29:11] [INFO] test_defaultcheck START:局域网页面默认项检查
[2017-09-06 11:29:21] [INFO] ###############
[2017-09-06 11:29:21] [INFO] None
[2017-09-06 11:29:21] [INFO] test_defaultcheck STOP
[2017-09-06 11:29:27] [INFO] test_dhcpclose START:关闭dhcp功能，检查页面租期和范围不展示
[2017-09-06 11:29:55] [INFO] test_dhcpclose STOP
[2017-09-06 11:29:59] [INFO] test_endlaniperror START:结束ip地址非法，提示信息检查
[2017-09-06 11:30:02] [INFO] 登录系统失败
[2017-09-06 11:30:02] [ERROR] Traceback (most recent call last):
  File "E:\pyproject\test_lan.py", line 193, in test_endlaniperror
    login(driver)
  File "E:\pyproject\public\logIn.py", line 10, in login
    driver.find_element_by_id("admin_Password1").send_keys(password)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 330, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 832, in find_element
    'value': value})['value']
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"admin_Password1"}
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)


[2017-09-06 11:30:08] [INFO] test_gotolan START:测试是否能成功跳转到局域网页面
[2017-09-06 11:30:30] [INFO] 到达局域网页面后的URL:http://192.168.0.1/DhcpServer.html
[2017-09-06 11:30:30] [INFO] test_gotolan STOP
[2017-09-06 11:30:36] [INFO] test_lanipinrange START:ip地址填正确是否可以保存成功
[2017-09-06 11:31:15] [INFO] test_noip Start:不输入IP 地址，检查提示信息
[2017-09-06 11:31:46] [INFO] test_noip STOP
[2017-09-06 11:31:50] [INFO] test_startipbigger START:开始ip地址大于结束ip地址，提示信息检查
[2017-09-06 11:32:21] [INFO] test_startipbigger STOP
[2017-09-06 11:32:26] [INFO] test_startlaniperror START:开始ip地址范围非法，提示信息检查
[2017-09-06 11:33:00] [INFO] test_wrongip:输入错误格式的ip地址，检查提示语
[2017-09-06 11:34:08] [INFO] test_wrongip STOP
[2017-09-06 11:34:12] [INFO] test_goto_login START:登录页面第一个测试用例，测试是否能成功跳转到登录页面
[2017-09-06 11:34:14] [INFO] URL 输入后的页面名称：DIR-823Pro
[2017-09-06 11:34:14] [INFO] test_goto_login STOP
[2017-09-06 11:34:19] [INFO] test_login_nopasswordenter START:不输入密码时的提示信息检查
[2017-09-06 11:34:27] [INFO] 请输入登录密码。
[2017-09-06 11:34:27] [INFO] test_login_nopasswordenter STOP
[2017-09-06 11:34:32] [INFO] test_login_right START:输入正确的密码验证是否能成功登录
[2017-09-06 11:34:34] [INFO] DIR-823Pro
[2017-09-06 11:34:34] [INFO] 未登录之前的URL: http://192.168.0.1/Login.html
[2017-09-06 11:34:44] [INFO] 登录成功后的URL:http://192.168.0.1/Home.html
[2017-09-06 11:34:44] [INFO] test_login_right STOP
[2017-09-06 11:34:49] [INFO] test_login_wrongpassword START:密码错误时的提示语检查
[2017-09-06 11:34:57] [INFO] 密码错误，请重新输入。
[2017-09-06 11:34:57] [INFO] test_login_wrongpassword STOP
[2017-09-06 11:35:02] [INFO]  test_cancelreboot START:点击重启路由器后，点击取消，确认可以成功取消
[2017-09-06 11:35:18] [ERROR] Traceback (most recent call last):
  File "E:\pyproject\test_systemsetup.py", line 339, in test_cancelreboot
    driver.find_element_by_id('wifiName_24').clear()
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidElementStateException: Message: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)


[2017-09-06 11:35:23] [ERROR] Traceback (most recent call last):
  File "E:\pyproject\test_systemsetup.py", line 349, in test_cancelreboot
    driver.find_element_by_id("saveconfirm2_5G").click()
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 78, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)


[2017-09-06 11:35:23] [INFO] test_cancelreboot STOP
[2017-09-06 11:35:28] [INFO] test_confirmpswdwrror START:确认密码和新密码不一致时的提示信息检查
[2017-09-06 11:36:06] [INFO] test_confirmpswdwrror STOP
[2017-09-06 11:36:11] [INFO] test_crrentpswderror START:原密码错误时的提示语检查
[2017-09-06 11:36:49] [INFO] test_crrentpswderror STOP
[2017-09-06 11:36:54] [INFO] test_firwareupdate START:固件格式错误时提示信息检查
[2017-09-06 11:37:37] [INFO] 开始用autoit3脚本控制选择本地文件
[2017-09-06 11:37:50] [ERROR] Traceback (most recent call last):
  File "E:\pyproject\test_systemsetup.py", line 290, in test_firwareupdate
    driver.find_element_by_id("btn_begin_upload").click()
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 78, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)


[2017-09-06 11:37:50] [INFO] test_firwareupdate STOP
[2017-09-06 11:37:55] [INFO]  test_logout START:测试退出功能
[2017-09-06 11:38:13] [INFO] test_logout STOP
[2017-09-06 11:38:18] [INFO] newpassworderror START:新密码格式错误时的，提示信息检查
